#!/bin/sh

case "$1" in
'start')
	# Pick appropriate stunnel client config
	name=`hostname`
	env=`nv --exactget name=$name --fields node_groups | grep tpkg_ | cut -d' ' -f2 | cut -d_ -f2`
	datacenter=`echo $name | cut -d. -f2`
	if [ -f /home/t/tpkg/config/stunnel-mysql_client.conf-${env}_${datacenter} ]
	then
		cp -p /home/t/tpkg/config/stunnel-mysql_client.conf-${env}_$datacenter /home/t/etc/stunnel/mysql_client.conf
		/home/t/etc/init.d/stunnel restart
	else
		echo "Stunnel client config for env $env and datacenter $datacenter not found" >&2
		exit 1
	fi

	# Start unicorn as user 't'
	(cd /home/t/tpkg && su t -s /bin/sh -c "/home/t/ruby/bin/unicorn_rails --env production --config-file config/unicorn.rb --daemonize")
	;;
'stop')
	# Stop stunnel
	/home/t/etc/init.d/stunnel stop
	rm -f /home/t/etc/stunnel/mysql_client.conf
	/home/t/etc/init.d/stunnel start
	
	# Stop unicorn
	if [ -f /home/t/tpkg/tmp/pids/unicorn.pid ]
	then
		kill `cat /home/t/tpkg/tmp/pids/unicorn.pid`
		rm -f /home/t/tpkg/tmp/pids/unicorn.pid
	fi
	;;
'restart')
	$0 stop
	# unicorn 0.8.1 has a bug and needs some time after stop to release sockets
	sleep 2
	$0 start
	;;
*)
	echo "Usage: $0 { start | stop | restart }"
	exit 1
	;;
esac
exit 0

