#!/bin/sh

case "$1" in
'start')
	# Start nginx
	/home/t/sbin/nginx -c /home/t/tpkg/config/nginx.conf
	;;
'stop')
	# Stop nginx
	if [ -f /home/t/var/run/nginx.pid ]
	then
		kill `cat /home/t/var/run/nginx.pid`
		rm -f /home/t/var/run/nginx.pid
	fi
	;;
'restart')
	$0 stop
	$0 start
	;;
*)
	echo "Usage: $0 { start | stop | restart }"
	exit 1
	;;
esac
exit 0

