#!/bin/sh

sed "s,%BASE%,$TPKG_HOME," $TPKG_HOME/etc/logrotate.conf > $TPKG_HOME/etc/logrotate.conf.new
test -s $TPKG_HOME/etc/logrotate.conf.new || exit 1
mv $TPKG_HOME/etc/logrotate.conf.new $TPKG_HOME/etc/logrotate.conf || exit 1

sed "s,%BASE%,$TPKG_HOME," $TPKG_HOME/etc/cron.d/logrotate > $TPKG_HOME/etc/cron.d/logrotate.new
test -s $TPKG_HOME/etc/cron.d/logrotate.new || exit 1
mv $TPKG_HOME/etc/cron.d/logrotate.new $TPKG_HOME/etc/cron.d/logrotate || exit 1

