#!/bin/sh

for file in $TPKG_HOME/etc/init.d/monit $TPKG_HOME/etc/monitrc $TPKG_HOME/etc/logrotate.d/monit
do
	sed "s,%BASE%,$TPKG_HOME," $file > $file.new
	test -s $file.new || exit 1
	if [ $file = $TPKG_HOME/etc/init.d/monit ]
	then
		chmod 755 $file.new || exit 1
	elif [ $file = $TPKG_HOME/etc/monitrc ]
	then
		chmod 400 $file.new || exit 1
	else
		chmod 444 $file.new || exit 1
	fi
	mv $file.new $file || exit 1
done

