#!/bin/sh
# Before running this script, do the following:
# First, download the jdk*.bin file.
# Second, execute that .bin file. That should extract and install
# files into something like "jdk1.6.0_24". Rename it to jdk1.6.0_24.x86_64
# to distinguish it from the 32bit version

set -e

PKG=jdk
VER=1.6.0_24
PKGVER=1
OS=`tpkg --qenv | grep 'Operating System' | awk '{print $NF}'`
if echo $OS | egrep 'RedHat|CentOS'
then
        # Save folks from having to build separate packages for Red Hat and
        # CentOS
        OSMAJOR=`echo $OS | cut -d- -f2`
        OS="RedHat-$OSMAJOR,CentOS-$OSMAJOR"
fi
ARCH=`tpkg --qenv | grep 'Architecture' | awk '{print $NF}'`

rm -rf $PKG-$VER
#tar zxvf $PKG-$VER.tar.gz
#cd $PKG-$VER
#make
src="$PKG$VER.x86_64"
dst="$PKG$VER"
pkgdir=`mktemp -d -t tpkg.XXXXXX`
cat ../tpkg.xml | \
	sed "s/NAME/$PKG/" | \
	sed "s/VERSION/$VER/" | \
	sed "s/PKGVER/$PKGVER/" | \
	sed "s/OS/$OS/" | \
	sed "s/ARCH/x86_64/" | \
	sed '/<files>/i\
<dependencies><dependency><name>libXtst</name><native/></dependency></dependencies>' \
	> $pkgdir/tpkg.xml

echo "Copying postinstall script over"
cp postinstall $pkgdir/postinstall
chmod 755 $pkgdir/postinstall

echo "Copying jdk files to staging directory"
mkdir -p $pkgdir/reloc
cp -r $src $pkgdir/reloc/$dst

# delete unnecesarry source code
rm $pkgdir/reloc/$dst/src.zip

echo "Setting up profile.d script"
mkdir -p $pkgdir/reloc/etc/profile.d
cp jdk.sh $pkgdir/reloc/etc/profile.d/

sed -i "s,%INSTALLED_DIR%,$dst," $pkgdir/reloc/etc/profile.d/jdk.sh 

# Make package
echo "Running tpkg --make"
tpkg --make $pkgdir

# Cleanup
rm -rf $pkgdir

