#!/bin/sh

sed "s,%BASE%,$TPKG_HOME," $TPKG_HOME/etc/profile.d/java.sh > $TPKG_HOME/etc/profile.d/java.sh.new
test -s $TPKG_HOME/etc/profile.d/java.sh.new || exit 1
mv $TPKG_HOME/etc/profile.d/java.sh.new $TPKG_HOME/etc/profile.d/java.sh || exit 1

# Ideally, we should be able to specify this in tpkg.xml. But tpkg doesn't handle
# ownership and permission for symlink. So we're manually setting it here
chown -h t:roleusers $TPKG_HOME/jdk_current
