#!/bin/sh

set -e

sed "s,%BASE%,$TPKG_HOME," $TPKG_HOME/etc/profile.d/java.sh > $TPKG_HOME/etc/profile.d/java.sh.new
test -s $TPKG_HOME/etc/profile.d/java.sh.new
mv $TPKG_HOME/etc/profile.d/java.sh.new $TPKG_HOME/etc/profile.d/java.sh

