#!/bin/sh

# This is a no-op in our environment as we always add all available groups to
# all systems.

# However, we need to take all the data fed to us so as not to trigger a
# SIGPIPE in the caller.
cat > /dev/null
